// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvrAJ-Wpbkj4trqg9SGH4HgTWWALPO8SY',
    appId: '1:663653799994:web:74b50ecc783d9605757d03',
    messagingSenderId: '663653799994',
    projectId: 'warnetps-manager',
    authDomain: 'warnetps-manager.firebaseapp.com',
    storageBucket: 'warnetps-manager.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQkBmZAphwl8OXXCrWrV3lzthEiU4YQtY',
    appId: '1:663653799994:android:cf4ebf6f4b01d74d757d03',
    messagingSenderId: '663653799994',
    projectId: 'warnetps-manager',
    storageBucket: 'warnetps-manager.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnRAeyZ6Keu-A0udEGv09TB9JY1QZtzKU',
    appId: '1:663653799994:ios:b442c8927bdf21bc757d03',
    messagingSenderId: '663653799994',
    projectId: 'warnetps-manager',
    storageBucket: 'warnetps-manager.firebasestorage.app',
    iosBundleId: 'com.example.warnetpsManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnRAeyZ6Keu-A0udEGv09TB9JY1QZtzKU',
    appId: '1:663653799994:ios:b442c8927bdf21bc757d03',
    messagingSenderId: '663653799994',
    projectId: 'warnetps-manager',
    storageBucket: 'warnetps-manager.firebasestorage.app',
    iosBundleId: 'com.example.warnetpsManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvrAJ-Wpbkj4trqg9SGH4HgTWWALPO8SY',
    appId: '1:663653799994:web:4c1b3c8e8ac97174757d03',
    messagingSenderId: '663653799994',
    projectId: 'warnetps-manager',
    authDomain: 'warnetps-manager.firebaseapp.com',
    storageBucket: 'warnetps-manager.firebasestorage.app',
  );
}
